version: '3'
services:
  db:
    env_file:
      - ./.env
    image: mysql:8.0.21
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/apache2/Dockerfile
    image: 'laravelapp'
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
